<div id="stripe-apple-pay-section">
    <div id="payment-request-button"></div>
</div>
<div id="stripe-apple-pay-result">
    <label><?php echo $this->__('Selected Card'); ?></label>
    <div>
        <span id="apple-pay-result-brand"></span>
        **** <span id="apple-pay-result-last4"></span>
    </div>
    <button type="button" class="button" title="Reset" name="reset" id="apple-pay-reset">
        <span><span><?php echo $this->__('Reset') ?></span></span>
    </button>
</div>
